### PR TITLE
249-A small change suggestion

### PR DESCRIPTION
**Pull request by ErdemT09**
My suggestion is that, instead of comparing the value of each char from the previous char, we can just compare them to the first char to get the same hash for different "shifted" strings .
Consider: "acfz" => This would correspond to "2,5,25"; so will be the string "zbey". As the difference from the first char must be the same in both strings if they are "shifted".

Additionally, I have also done some auto-formatting. That's why there seems to be these many changes.

### CODE REVIEW

**Comment by altayhunoglu** [comment]
Although both solutions take the same time (9ms), using the first char as a standpoint is a smart idea.
 
 Another approach is, to calculate the difference for the first char and apply it to all: (It takes 1ms)
 
```
   public String getKey(String str) {
        int diff = str.charAt(0) - 'a';
        char[] chars = str.toCharArray();
        for (int i = 0; i < chars.length; i++) {
            chars[i] = chars[i] - diff < 'a' ? (char)(chars[i] - diff + 26) : (char)(chars[i] - diff);
        }
        return String.valueOf(chars);
    }
```
In this picture, diff = 25.
Then we apply the same subtraction to all chars and estimate their first state (before any shifting process)

IMG-1598

**Comment by ErdemT09** [comment]
I think that we can actually get rid of the ternary operator by inserting the modulus operator:
 public String getKey(String str) {
        int diff = str.charAt(0) - 'a';
        char[] chars = str.toCharArray();
        for (int i = 0; i < chars.length; i++) {
            chars[i] = (char)((chars[i] - diff + 26)%26);
        }
        return String.valueOf(chars);
    }

Is this better?

**Comment by altayhunoglu** [comment]
> public String getKey(String str) {
>         int diff = str.charAt(0) - 'a';
>         char[] chars = str.toCharArray();
>         for (int i = 0; i < chars.length; i++) {
>             chars[i] = (char)((chars[i] - diff + 26)%26);
>         }
>         return String.valueOf(chars);
>     }

Yep. Great idea Erdem.

We can take this.

image

**Comment by ErdemT09** [comment]
Applying it then.

**Review by altayhunoglu — APPROVED** [review]
Great refactoring. Thanks.

**Pull request merged**
