### PR TITLE
1087-List solution

### PR DESCRIPTION
**Pull request by ErdemT09**
This new solution places the strings in a list and sorts them each time. Would it be more efficient just to sort at the end and not in every method call?

### CODE REVIEW

**Comment by altayhunoglu** [comment]
I think currently it is sorting at the end, and it looks fine to me.

**Review by altayhunoglu — APPROVED** [review]
Quite fine Erdem. Thank you.

image

**Comment by ErdemT09** [comment]
I will actually remove the re-sorting of the list each time and add it. That should be faster.
```
public String[] expand(String S) {
    return expandRecursive(S, true);
  }

  private String[] expandRecursive(String S, boolean sort) {
    int n = S.length();
    if (n == 0) {
      return new String[] { "" };
    }
    if (n == 1) {
      return new String[] { S };
    }

    List<String> res = new ArrayList<>();
    if (S.charAt(0) == '{') {
      int i = 0;
      while (i < S.length()) {
        if (S.charAt(i) == '}') {
          break;
        }
        i++;
      }
      String[] leftStrs = S.substring(1, i).split(",");
      String[] rightStrs = expandRecursive(S.substring(i + 1), false);
      for (String lStr : leftStrs) {
        for (String rStr : rightStrs) {
          res.add(lStr + rStr);
        }
      }
    } else {
      String[] rightStrs = expandRecursive(S.substring(1), false);
      for (String rStr : rightStrs) {
        res.add(S.charAt(0) + rStr);
      }
    }
    if (sort) {
      Collections.sort(res);
    }
    return res.toArray(new String[0]);
  }
```

**Comment by altayhunoglu** [comment]
Hello Erdem,

It is almost the same:
image

**Comment by ErdemT09** [comment]
Then I am merging with the current list solution as it is simpler than the other.

**Pull request merged**
